import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const root = process.cwd();
const postsDir = path.join(root, 'posts');
const outFile = path.join(root, 'src', 'lib', 'posts.generated.ts');

const entries = fs.readdirSync(postsDir)
  .filter((name) => name.endsWith('.md'))
  .map((name) => {
    const full = path.join(postsDir, name);
    const raw = fs.readFileSync(full, 'utf8');
    const { data, content } = matter(raw);
    const slug = name.replace(/\.md$/, '');
    return {
      slug,
      title: data.title || 'Untitled',
      date: data.date || new Date().toISOString(),
      excerpt: data.excerpt || '',
      tags: Array.isArray(data.tags) ? data.tags : [],
      cover: data.cover || undefined,
      content,
    };
  });

const sorted = entries.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

const body = `// Generated by scripts/generate-posts.mjs\n` +
`export const posts = ${JSON.stringify(sorted, null, 2)} as const;\n`;

fs.writeFileSync(outFile, body, 'utf8');
console.log(`Generated ${outFile} (${sorted.length} posts)`);
